/*
 * This file is generated by jOOQ.
 */
package app.jooq;


import app.jooq.tables.Book;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in bookshelf
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>bookshelf.book</code>.
     */
    public static final Book BOOK = app.jooq.tables.Book.BOOK;
}
